---
- name: Set OSPF RID
  nclu:
    commands:
    - add ospf router-id {{ rid }}
    atomic: true
    description: "Set OSPF RID"

- name: Enable OSPF
  nclu:
    commands:
    - add ospf network {{ item.prefix }} area {{ item.area }}
    atomic: true
    description: "Enable OSPF"
  loop:
    - { prefix: 192.168.0.0/16, area: 0.0.0.0 }
    - { prefix: 10.0.0.0/24, area: 0.0.0.0 }