---
- name: Enable OSPF for leafs
  nclu:
    commands:
    - add ospf router-id {{ rid }}
    - add interface {{ item.iface }} ip address {{ loopback }}
    - add interface {{ item.iface }} ospf area {{ item.area }}
    - add interface {{ item.iface }} ospf network point-to-point
    atomic: true
    description: "Enable OSPF for leafs"
  loop:
    - { iface: swp49, area: 0.0.0.0 }
    - { iface: swp50, area: 0.0.0.0 }
    - { iface: swp51, area: 0.0.0.0 }
    - { iface: swp52, area: 0.0.0.0 }

- name: Configure and advertise interfaces to servers
  nclu:
    commands:
    - add interface {{ ifaceserver }} ip address {{ ifaceserverip }}
    - add ospf passive-interface {{ ifaceserver }}
    - add interface {{ ifaceserver }} ospf area {{ item.area }}
    atomic: true
    description: "Configure and advertise interfaces to servers"
  loop:
    - { area: 0.0.0.0 }
